---
- hosts: 192.168.43.237
  tasks:
    - name: updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          
    - name: systeminfo
      win_command: systeminfo
      register: systeminfo_cmd
      
    - name: Install git from specified repository
      win_chocolatey:
        name: git
        source: https://chocolatey.org/api/v2
        
    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest
      
    - debug:
        msg: '{{systeminfo_cmd.stdout_lines}}'
