---
- hosts: 192.168.43.237
  tasks:
    - name: updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          
    - name: systeminfo
      win_command: systeminfo
      register: systeminfo_cmd
      
    - debug:
        msg: '{{systeminfo_cmd.stdout_lines}}'
